project:
  title: "hmw_1_data_analysis"

authors:
  - name: "Oscar Plaisant"
    note: "22500288"
    url: "https://osk42.quarto.pub"
    email: "oscar.plaisant@etu.u-paris.fr"
  - name: "Anthony Saab"
    note: "22525585"
    url: "https://sites.google.com/view/saabism/portfolio"
    email: "anthony.saab@etu.u-paris.fr"
  - name: "Yousra Tersi"
    note: "22513160"
    email: "yousra.tersi@etu.u-paris.fr"

format:
  html:
    theme: lux
    css: style.css
  revealjs:
    css: style.css
  ipynb:
    ipynb-ouput: all  # compute all cells when rendering a notebook

render: # which files to render
  - report.qmd


# output-dir: "outdir"

execute: 
  #eval: true
  #echo: false
  collapse: false
  cache: true  # cache the notebook, requires jupyter-cache
  daemon: true  # don't restart the kenel at each render



engine: jupyter

license: CC BY-NC

